export const CHAT_GET_REQUEST = 'CHAT_GET_REQUEST';
export const CHAT_GET_SUCCESS = 'CHAT_GET_SUCCESS';
export const CHAT_GET_FAIL = 'CHAT_GET_FAIL';

export const CHAT_POST_REQUEST = 'CHAT_POST_REQUEST';
export const CHAT_POST_SUCCESS = 'CHAT_POST_SUCCESS';
export const CHAT_POST_FAIL = 'CHAT_POST_FAIL';